package com.spark_kafka

import java.util
import java.util.regex.Pattern

import org.apache.kafka.clients.producer.ProducerConfig

object Utilities {

  //Map URLs to their categories.
  val insuranceCategoryMap = Map(
    "http://www.thehartford.com/individual&families/vehicleinsurance" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance" -> "Flood Insurance",
    "http://www.thehartford.com/individual&families/umbrellainsurance" -> "Umbrella Insurance",
    "http://www.thehartford.com/individual&families/bundleandsave" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/vehicleinsurance/featuresandbenefits" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/vehicleinsurance/discountsandbenfits" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/vehicleinsurance/coverageoptions" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/vehicleinsurance/getquotes" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/vehicleinsurance/userdetails" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/vehicleinsurance/onlinequotes" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/vehicleinsurance/getcalled" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/vehicleinsurance/claims" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/vehicleinsurance/articles" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/vehicleinsurance/videos" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/vehicleinsurance/FAQ" -> "Vehicle Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance/featuresandbenefits" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance/discountsandbenfits" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance/coverageoptions" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance/getquotes" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance/userdetails" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance/onlinequotes" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance/getcalled" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance/claims" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance/articles" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance/videos" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance/FAQ" -> "Home Owner Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance/featuresandbenefits" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance/discountsandbenfits" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance/coverageoptions" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance/getquotes" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance/userdetails" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance/onlinequotes" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance/getcalled" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance/claims" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance/articles" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance/videos" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/condoinsurance/FAQ" -> "Condo Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance/featuresandbenefits" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance/discountsandbenfits" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance/coverageoptions" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance/getquotes" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance/userdetails" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance/onlinequotes" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance/getcalled" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance/claims" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance/articles" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance/videos" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/rentersinsurance/FAQ" -> "Renters Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance/featuresandbenefits" -> "Flood Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance/discountsandbenfits" -> "Flood Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance/coverageoptions" -> "Flood Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance/getquotes" -> "Flood Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance/userdetails" -> "Flood Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance/onlinequotes" -> "Flood Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance/getcalled" -> "Flood Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance/claims" -> "Flood Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance/articles" -> "Flood Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance/videos" -> "Flood Insurance",
    "http://www.thehartford.com/individual&families/floodinsurance/FAQ" -> "Flood Insurance"
  )

  val referralCategoryMap = Map(
    "https://www.speedyads.com" -> "ads",
    "https://www.bidvertiser.com" -> "ads",
    "https://www.google.com/adsense" -> "ads",
    "https://www.google.com/adservecises" -> "ads",
    "https://www.google.com" -> "search engines",
    "https://www.search.aol.com" -> "search engines",
    "https://www.bing.com" -> "search engines",
    "https://www.yahoo.com" -> "search engines",
    "https://www.ask.com" -> "search engines",
    "https://www.baidu.com" -> "search engines",
    "https://duckduckgo.com" -> "search engines",
    "https://www.dogpile.com" -> "search engines",
    "https://www.facebook.com" -> "social media",
    "https://www.twitter.com" -> "social media",
    "https://www.youtube.com" -> "social media",
    "https://www.quora.com" -> "social media",
    "https://www.linkedin.com" -> "social media",
    "https://www.instagram.com" -> "social media",
    "https://www.tumblr.com" -> "social media",
    "https://www.pinterest.com" -> "social media",
    "https://www.usdaily.com" -> "news channels",
    "https://onlin.wsj.com" -> "news channels",
    "https://www.nytimes.com" -> "news channels",
    "https://mail.google.com" -> "emails",
    "https://mail.yahoo.com" -> "emails",
    "https://www.live.com" -> "emails",
    "https://inbox.google.com" -> "emails",
    "http://www.thehartford.com" -> "direct",
    "http://www.thehartford.com" -> "direct",
    "http://www.thehartford.com/individual&families" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance" -> "direct",
    "http://www.thehartford.com/individual&families/umbrellainsurance" -> "direct",
    "http://www.thehartford.com/individual&families/bundleandsave" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance/featuresandbenefits" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance/discountsandbenfits" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance/coverageoptions" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance/getquotes" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance/userdetails" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance/onlinequotes" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance/getcalled" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance/claims" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance/articles" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance/videos" -> "direct",
    "http://www.thehartford.com/individual&families/vehicleinsurance/FAQ" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance/featuresandbenefits" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance/discountsandbenfits" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance/coverageoptions" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance/getquotes" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance/userdetails" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance/onlinequotes" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance/getcalled" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance/claims" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance/articles" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance/videos" -> "direct",
    "http://www.thehartford.com/individual&families/homeownerinsurance/FAQ" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance/featuresandbenefits" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance/discountsandbenfits" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance/coverageoptions" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance/getquotes" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance/userdetails" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance/onlinequotes" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance/getcalled" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance/claims" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance/articles" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance/videos" -> "direct",
    "http://www.thehartford.com/individual&families/condoinsurance/FAQ" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance/featuresandbenefits" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance/discountsandbenfits" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance/coverageoptions" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance/getquotes" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance/userdetails" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance/onlinequotes" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance/getcalled" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance/claims" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance/articles" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance/videos" -> "direct",
    "http://www.thehartford.com/individual&families/rentersinsurance/FAQ" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance/featuresandbenefits" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance/discountsandbenfits" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance/coverageoptions" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance/getquotes" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance/userdetails" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance/onlinequotes" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance/getcalled" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance/claims" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance/articles" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance/videos" -> "direct",
    "http://www.thehartford.com/individual&families/floodinsurance/FAQ" -> "direct",
    "http://www.thehartford.com/blog" -> "direct",
    "http://www.thehartford.com/blog/signup" -> "direct",
    "http://www.thehartford.com/blog/about" -> "direct",
    "http://www.thehartford.com/blog/page1" -> "direct",
    "http://www.thehartford.com/blog/page2" -> "direct",
    "http://www.thehartford.com/blog/page3" -> "direct",
    "http://www.thehartford.com/blog/page4" -> "direct",
    "http://www.thehartford.com/blog/page5" -> "direct",
    "http://www.thehartford.com/blog/page6" -> "direct",
    "http://www.thehartford.com/blog/page7" -> "direct",
    "http://www.thehartford.com/blog/page8" -> "direct",
    "http://www.thehartford.com/blog/page9" -> "direct",
    "http://www.thehartford.com/blog/page10" -> "direct",
    "http://www.thehartford.com/blog/page11" -> "direct",
    "http://www.thehartford.com/blog/page12" -> "direct",
    "http://www.thehartford.com/blog/page13" -> "direct",
    "http://www.thehartford.com/blog/page14" -> "direct",
    "http://www.thehartford.com/blog/page15" -> "direct",
    "http://www.thehartford.com/blog/page16" -> "direct",
    "http://www.thehartford.com/blog/page17" -> "direct",
    "http://www.thehartford.com/blog/page18" -> "direct",
    "http://www.thehartford.com/blog/page19" -> "direct",
    "http://www.thehartford.com/blog/page20" -> "direct",
    "http://www.thehartford.com/blog/page21" -> "direct",
    "http://www.thehartford.com/blog/page22" -> "direct",
    "http://www.thehartford.com/blog/page23" -> "direct",
    "http://www.thehartford.com/blog/page24" -> "direct",
    "http://www.thehartford.com/blog/page25" -> "direct",
    "http://www.thehartford.com/corporate" -> "direct",
    "http://www.thehartford.com/corporate/comapany" -> "direct",
    "http://www.thehartford.com/corporate/comapany/whoweare" -> "direct",
    "http://www.thehartford.com/corporate/comapany/howwemeetyourneeds" -> "direct",
    "http://www.thehartford.com/corporate/comapany/whatsetsusapart" -> "direct",
    "http://www.thehartford.com/corporate/contactus" -> "direct",
    "http://www.thehartford.com/corporate/news" -> "direct"
  )

  val shortenedLandingPagesMap = Map(
    "http://www.thehartford.com" -> "/homepage/e",
    "http://www.thehartford.com/individual&families" -> "/individual&families/e",
    "http://www.thehartford.com/individual&families/vehicleinsurance" -> "/vehicleinsurance/e",
    "http://www.thehartford.com/individual&families/homeownerinsurance" -> "/homeownerinsurance/e",
    "http://www.thehartford.com/individual&families/condoinsurance" -> "/condoinsurance/e",
    "http://www.thehartford.com/individual&families/rentersinsurance" -> "/rentersinsurance/e",
    "http://www.thehartford.com/individual&families/floodinsurance" -> "/floodinsurance/e",
    "http://www.thehartford.com/individual&families/umbrellainsurance" -> "/umbrellainsurance/e",
    "http://www.thehartford.com/individual&families/bundleandsave" -> "/bundleandsave/e",
    "http://www.thehartford.com/individual&families/vehicleinsurance/featuresandbenefits" -> "/vehicleinsurance/featuresandbenefits",
    "http://www.thehartford.com/individual&families/vehicleinsurance/discountsandbenfits" -> "/vehicleinsurance/discountsandbenfits",
    "http://www.thehartford.com/individual&families/vehicleinsurance/coverageoptions" -> "/vehicleinsurance/coverageoptions",
    "http://www.thehartford.com/individual&families/vehicleinsurance/getquotes" -> "/vehicleinsurance/getquotes",
    "http://www.thehartford.com/individual&families/vehicleinsurance/userdetails" -> "/vehicleinsurance/userdetails",
    "http://www.thehartford.com/individual&families/vehicleinsurance/onlinequotes" -> "/vehicleinsurance/onlinequotes",
    "http://www.thehartford.com/individual&families/vehicleinsurance/getcalled" -> "/vehicleinsurance/getcalled",
    "http://www.thehartford.com/individual&families/vehicleinsurance/claims" -> "/vehicleinsurance/claims",
    "http://www.thehartford.com/individual&families/vehicleinsurance/articles" -> "/vehicleinsurance/articles",
    "http://www.thehartford.com/individual&families/vehicleinsurance/videos" -> "/vehicleinsurance/videos",
    "http://www.thehartford.com/individual&families/vehicleinsurance/FAQ" -> "/vehicleinsurance/FAQ",
    "http://www.thehartford.com/individual&families/homeownerinsurance/featuresandbenefits" -> "/homeownerinsurance/featuresandbenefits",
    "http://www.thehartford.com/individual&families/homeownerinsurance/discountsandbenfits" -> "/homeownerinsurance/discountsandbenfits",
    "http://www.thehartford.com/individual&families/homeownerinsurance/coverageoptions" -> "/homeownerinsurance/coverageoptions",
    "http://www.thehartford.com/individual&families/homeownerinsurance/getquotes" -> "/homeownerinsurance/getquotes",
    "http://www.thehartford.com/individual&families/homeownerinsurance/userdetails" -> "/homeownerinsurance/userdetails",
    "http://www.thehartford.com/individual&families/homeownerinsurance/onlinequotes" -> "/homeownerinsurance/onlinequotes",
    "http://www.thehartford.com/individual&families/homeownerinsurance/getcalled" -> "/homeownerinsurance/getcalled",
    "http://www.thehartford.com/individual&families/homeownerinsurance/claims" -> "/homeownerinsurance/claims",
    "http://www.thehartford.com/individual&families/homeownerinsurance/articles" -> "/homeownerinsurance/articles",
    "http://www.thehartford.com/individual&families/homeownerinsurance/videos" -> "/homeownerinsurance/videos",
    "http://www.thehartford.com/individual&families/homeownerinsurance/FAQ" -> "/homeownerinsurance/FAQ",
    "http://www.thehartford.com/individual&families/condoinsurance/featuresandbenefits" -> "/condoinsurance/featuresandbenefits",
    "http://www.thehartford.com/individual&families/condoinsurance/discountsandbenfits" -> "/condoinsurance/discountsandbenfits",
    "http://www.thehartford.com/individual&families/condoinsurance/coverageoptions" -> "/condoinsurance/coverageoptions",
    "http://www.thehartford.com/individual&families/condoinsurance/getquotes" -> "/condoinsurance/getquotes",
    "http://www.thehartford.com/individual&families/condoinsurance/userdetails" -> "/condoinsurance/userdetails",
    "http://www.thehartford.com/individual&families/condoinsurance/onlinequotes" -> "/condoinsurance/onlinequotes",
    "http://www.thehartford.com/individual&families/condoinsurance/getcalled" -> "/condoinsurance/getcalled",
    "http://www.thehartford.com/individual&families/condoinsurance/claims" -> "/condoinsurance/claims",
    "http://www.thehartford.com/individual&families/condoinsurance/articles" -> "/condoinsurance/articles",
    "http://www.thehartford.com/individual&families/condoinsurance/videos" -> "/condoinsurance/videos",
    "http://www.thehartford.com/individual&families/condoinsurance/FAQ" -> "/condoinsurance/FAQ",
    "http://www.thehartford.com/individual&families/rentersinsurance/featuresandbenefits" -> "/rentersinsurance/featuresandbenefits",
    "http://www.thehartford.com/individual&families/rentersinsurance/discountsandbenfits" -> "/rentersinsurance/discountsandbenfits",
    "http://www.thehartford.com/individual&families/rentersinsurance/coverageoptions" -> "/rentersinsurance/coverageoptions",
    "http://www.thehartford.com/individual&families/rentersinsurance/getquotes" -> "/rentersinsurance/getquotes",
    "http://www.thehartford.com/individual&families/rentersinsurance/userdetails" -> "/rentersinsurance/userdetails",
    "http://www.thehartford.com/individual&families/rentersinsurance/onlinequotes" -> "/rentersinsurance/onlinequotes",
    "http://www.thehartford.com/individual&families/rentersinsurance/getcalled" -> "/rentersinsurance/getcalled",
    "http://www.thehartford.com/individual&families/rentersinsurance/claims" -> "/rentersinsurance/claims",
    "http://www.thehartford.com/individual&families/rentersinsurance/articles" -> "/rentersinsurance/articles",
    "http://www.thehartford.com/individual&families/rentersinsurance/videos" -> "/rentersinsurance/videos",
    "http://www.thehartford.com/individual&families/rentersinsurance/FAQ" -> "/rentersinsurance/FAQ",
    "http://www.thehartford.com/individual&families/floodinsurance/featuresandbenefits" -> "/floodinsurance/featuresandbenefits",
    "http://www.thehartford.com/individual&families/floodinsurance/discountsandbenfits" -> "/floodinsurance/discountsandbenfits",
    "http://www.thehartford.com/individual&families/floodinsurance/coverageoptions" -> "/floodinsurance/coverageoptions",
    "http://www.thehartford.com/individual&families/floodinsurance/getquotes" -> "/floodinsurance/getquotes",
    "http://www.thehartford.com/individual&families/floodinsurance/userdetails" -> "/floodinsurance/userdetails",
    "http://www.thehartford.com/individual&families/floodinsurance/onlinequotes" -> "/floodinsurance/onlinequotes",
    "http://www.thehartford.com/individual&families/floodinsurance/getcalled" -> "/floodinsurance/getcalled",
    "http://www.thehartford.com/individual&families/floodinsurance/claims" -> "/floodinsurance/claims",
    "http://www.thehartford.com/individual&families/floodinsurance/articles" -> "/floodinsurance/articles",
    "http://www.thehartford.com/individual&families/floodinsurance/videos" -> "/floodinsurance/videos",
    "http://www.thehartford.com/individual&families/floodinsurance/FAQ" -> "/floodinsurance/FAQ",
    "http://www.thehartford.com/blog" -> "/blog/e",
    "http://www.thehartford.com/blog/signup" -> "/blog/e",
    "http://www.thehartford.com/blog/about" -> "/blog/e",
    "http://www.thehartford.com/blog/page1" -> "/blog/e",
    "http://www.thehartford.com/blog/page2" -> "/blog/e",
    "http://www.thehartford.com/blog/page3" -> "/blog/e",
    "http://www.thehartford.com/blog/page4" -> "/blog/e",
    "http://www.thehartford.com/blog/page5" -> "/blog/e",
    "http://www.thehartford.com/blog/page6" -> "/blog/e",
    "http://www.thehartford.com/blog/page7" -> "/blog/e",
    "http://www.thehartford.com/blog/page8" -> "/blog/e",
    "http://www.thehartford.com/blog/page9" -> "/blog/e",
    "http://www.thehartford.com/blog/page10" -> "/blog/e",
    "http://www.thehartford.com/blog/page11" -> "/blog/e",
    "http://www.thehartford.com/blog/page12" -> "/blog/e",
    "http://www.thehartford.com/blog/page13" -> "/blog/e",
    "http://www.thehartford.com/blog/page14" -> "/blog/e",
    "http://www.thehartford.com/blog/page15" -> "/blog/e",
    "http://www.thehartford.com/blog/page16" -> "/blog/e",
    "http://www.thehartford.com/blog/page17" -> "/blog/e",
    "http://www.thehartford.com/blog/page18" -> "/blog/e",
    "http://www.thehartford.com/blog/page19" -> "/blog/e",
    "http://www.thehartford.com/blog/page20" -> "/blog/e",
    "http://www.thehartford.com/blog/page21" -> "/blog/e",
    "http://www.thehartford.com/blog/page22" -> "/blog/e",
    "http://www.thehartford.com/blog/page23" -> "/blog/e",
    "http://www.thehartford.com/blog/page24" -> "/blog/e",
    "http://www.thehartford.com/blog/page25" -> "/blog/e",
    "http://www.thehartford.com/corporate" -> "/corporate/e",
    "http://www.thehartford.com/corporate/comapany" -> "/corporate/e",
    "http://www.thehartford.com/corporate/comapany/whoweare" -> "/corporate/e",
    "http://www.thehartford.com/corporate/comapany/howwemeetyourneeds" -> "/corporate/e",
    "http://www.thehartford.com/corporate/comapany/whatsetsusapart" -> "/corporate/e",
    "http://www.thehartford.com/corporate/contactus" -> "/corporate/e",
    "http://www.thehartford.com/corporate/news" -> "/corporate/e"
  )

  val shortenedReferralPagesMap = Map(
    "https://www.speedyads.com" -> "speedyads.com",
    "https://www.bidvertiser.com" -> "bidvertiser.com",
    "https://www.google.com/adsense" -> "google.com/adsense",
    "https://www.google.com/adservecises" -> "google.com/adservecises",
    "https://www.google.com" -> "google.com",
    "https://www.search.aol.com" -> "search.aol.com",
    "https://www.bing.com" -> "bing.com",
    "https://www.yahoo.com" -> "yahoo.com",
    "https://www.ask.com" -> "ask.com",
    "https://www.baidu.com" -> "baidu.com",
    "https://duckduckgo.com" -> "duckgo.com",
    "https://www.dogpile.com" -> "dogpile.com",
    "https://www.facebook.com" -> "facebook.com",
    "https://www.twitter.com" -> "twitter.com",
    "https://www.youtube.com" -> "youtube.com",
    "https://www.quora.com" -> "quora.com",
    "https://www.linkedin.com" -> "linkedin.com",
    "https://www.instagram.com" -> "instagram.com",
    "https://www.tumblr.com" -> "tumblr.com",
    "https://www.pinterest.com" -> "pinterest.com",
    "https://www.usdaily.com" -> "usdaily.com",
    "https://onlin.wsj.com" -> "onlin.wsj.com",
    "https://www.nytimes.com" -> "nytimes.com",
    "https://mail.google.com" -> "google.com",
    "https://mail.yahoo.com" -> "yahoo.com",
    "https://www.live.com" -> "live.com",
    "https://inbox.google.com" -> "google.com",
    "http://www.thehartford.com" -> "thehartford.com",
    "http://www.thehartford.com/individual&families" -> "/individual&families",
    "http://www.thehartford.com/individual&families/vehicleinsurance" -> "/vehicleinsurance",
    "http://www.thehartford.com/individual&families/homeownerinsurance" -> "/homeownerinsurance",
    "http://www.thehartford.com/individual&families/condoinsurance" -> "/condoinsurance",
    "http://www.thehartford.com/individual&families/rentersinsurance" -> "/rentersinsurance",
    "http://www.thehartford.com/individual&families/floodinsurance" -> "/floodinsurance",
    "http://www.thehartford.com/individual&families/umbrellainsurance" -> "/umbrellainsurance",
    "http://www.thehartford.com/individual&families/bundleandsave" -> "/bundleandsave",
    "http://www.thehartford.com/individual&families/vehicleinsurance/featuresandbenefits" -> "/vehicleinsurance/featuresandbenefits",
    "http://www.thehartford.com/individual&families/vehicleinsurance/discountsandbenfits" -> "/vehicleinsurance/discountsandbenfits",
    "http://www.thehartford.com/individual&families/vehicleinsurance/coverageoptions" -> "/vehicleinsurance/coverageoptions",
    "http://www.thehartford.com/individual&families/vehicleinsurance/getquotes" -> "/vehicleinsurance/getquotes",
    "http://www.thehartford.com/individual&families/vehicleinsurance/userdetails" -> "/vehicleinsurance/userdetails",
    "http://www.thehartford.com/individual&families/vehicleinsurance/onlinequotes" -> "/vehicleinsurance/onlinequotes",
    "http://www.thehartford.com/individual&families/vehicleinsurance/getcalled" -> "/vehicleinsurance/getcalled",
    "http://www.thehartford.com/individual&families/vehicleinsurance/claims" -> "/vehicleinsurance/claims",
    "http://www.thehartford.com/individual&families/vehicleinsurance/articles" -> "/vehicleinsurance/articles",
    "http://www.thehartford.com/individual&families/vehicleinsurance/videos" -> "/vehicleinsurance/videos",
    "http://www.thehartford.com/individual&families/vehicleinsurance/FAQ" -> "/vehicleinsurance/FAQ",
    "http://www.thehartford.com/individual&families/homeownerinsurance/featuresandbenefits" -> "/homeownerinsurance/featuresandbenefits",
    "http://www.thehartford.com/individual&families/homeownerinsurance/discountsandbenfits" -> "/homeownerinsurance/discountsandbenfits",
    "http://www.thehartford.com/individual&families/homeownerinsurance/coverageoptions" -> "/homeownerinsurance/coverageoptions",
    "http://www.thehartford.com/individual&families/homeownerinsurance/getquotes" -> "/homeownerinsurance/getquotes",
    "http://www.thehartford.com/individual&families/homeownerinsurance/userdetails" -> "/homeownerinsurance/userdetails",
    "http://www.thehartford.com/individual&families/homeownerinsurance/onlinequotes" -> "/homeownerinsurance/onlinequotes",
    "http://www.thehartford.com/individual&families/homeownerinsurance/getcalled" -> "/homeownerinsurance/getcalled",
    "http://www.thehartford.com/individual&families/homeownerinsurance/claims" -> "/homeownerinsurance/claims",
    "http://www.thehartford.com/individual&families/homeownerinsurance/articles" -> "/homeownerinsurance/articles",
    "http://www.thehartford.com/individual&families/homeownerinsurance/videos" -> "/homeownerinsurance/videos",
    "http://www.thehartford.com/individual&families/homeownerinsurance/FAQ" -> "/homeownerinsurance/FAQ",
    "http://www.thehartford.com/individual&families/condoinsurance/featuresandbenefits" -> "/condoinsurance/featuresandbenefits",
    "http://www.thehartford.com/individual&families/condoinsurance/discountsandbenfits" -> "/condoinsurance/discountsandbenfits",
    "http://www.thehartford.com/individual&families/condoinsurance/coverageoptions" -> "/condoinsurance/coverageoptions",
    "http://www.thehartford.com/individual&families/condoinsurance/getquotes" -> "/condoinsurance/getquotes",
    "http://www.thehartford.com/individual&families/condoinsurance/userdetails" -> "/condoinsurance/userdetails",
    "http://www.thehartford.com/individual&families/condoinsurance/onlinequotes" -> "/condoinsurance/onlinequotes",
    "http://www.thehartford.com/individual&families/condoinsurance/getcalled" -> "/condoinsurance/getcalled",
    "http://www.thehartford.com/individual&families/condoinsurance/claims" -> "/condoinsurance/claims",
    "http://www.thehartford.com/individual&families/condoinsurance/articles" -> "/condoinsurance/articles",
    "http://www.thehartford.com/individual&families/condoinsurance/videos" -> "/condoinsurance/videos",
    "http://www.thehartford.com/individual&families/condoinsurance/FAQ" -> "/condoinsurance/FAQ",
    "http://www.thehartford.com/individual&families/rentersinsurance/featuresandbenefits" -> "/rentersinsurance/featuresandbenefits",
    "http://www.thehartford.com/individual&families/rentersinsurance/discountsandbenfits" -> "/rentersinsurance/discountsandbenfits",
    "http://www.thehartford.com/individual&families/rentersinsurance/coverageoptions" -> "/rentersinsurance/coverageoptions",
    "http://www.thehartford.com/individual&families/rentersinsurance/getquotes" -> "/rentersinsurance/getquotes",
    "http://www.thehartford.com/individual&families/rentersinsurance/userdetails" -> "/rentersinsurance/userdetails",
    "http://www.thehartford.com/individual&families/rentersinsurance/onlinequotes" -> "/rentersinsurance/onlinequotes",
    "http://www.thehartford.com/individual&families/rentersinsurance/getcalled" -> "/rentersinsurance/getcalled",
    "http://www.thehartford.com/individual&families/rentersinsurance/claims" -> "/rentersinsurance/claims",
    "http://www.thehartford.com/individual&families/rentersinsurance/articles" -> "/rentersinsurance/articles",
    "http://www.thehartford.com/individual&families/rentersinsurance/videos" -> "/rentersinsurance/videos",
    "http://www.thehartford.com/individual&families/rentersinsurance/FAQ" -> "/rentersinsurance/FAQ",
    "http://www.thehartford.com/individual&families/floodinsurance/featuresandbenefits" -> "/floodinsurance/featuresandbenefits",
    "http://www.thehartford.com/individual&families/floodinsurance/discountsandbenfits" -> "/floodinsurance/discountsandbenfits",
    "http://www.thehartford.com/individual&families/floodinsurance/coverageoptions" -> "/floodinsurance/coverageoptions",
    "http://www.thehartford.com/individual&families/floodinsurance/getquotes" -> "/floodinsurance/getquotes",
    "http://www.thehartford.com/individual&families/floodinsurance/userdetails" -> "/floodinsurance/userdetails",
    "http://www.thehartford.com/individual&families/floodinsurance/onlinequotes" -> "/floodinsurance/onlinequotes",
    "http://www.thehartford.com/individual&families/floodinsurance/getcalled" -> "/floodinsurance/getcalled",
    "http://www.thehartford.com/individual&families/floodinsurance/claims" -> "/floodinsurance/claims",
    "http://www.thehartford.com/individual&families/floodinsurance/articles" -> "/floodinsurance/articles",
    "http://www.thehartford.com/individual&families/floodinsurance/videos" -> "/floodinsurance/videos",
    "http://www.thehartford.com/individual&families/floodinsurance/FAQ" -> "/floodinsurance/FAQ",
    "http://www.thehartford.com/blog" -> "thehartford.com/blog",
    "http://www.thehartford.com/blog/signup" -> "thehartford.com/blog/signup",
    "http://www.thehartford.com/blog/about" -> "thehartford.com/blog/about",
    "http://www.thehartford.com/blog/page1" -> "thehartford.com/blog/page1",
    "http://www.thehartford.com/blog/page2" -> "thehartford.com/blog/page2",
    "http://www.thehartford.com/blog/page3" -> "thehartford.com/blog/page3",
    "http://www.thehartford.com/blog/page4" -> "thehartford.com/blog/page4",
    "http://www.thehartford.com/blog/page5" -> "thehartford.com/blog/page5",
    "http://www.thehartford.com/blog/page6" -> "thehartford.com/blog/page6",
    "http://www.thehartford.com/blog/page7" -> "thehartford.com/blog/page7",
    "http://www.thehartford.com/blog/page8" -> "thehartford.com/blog/page8",
    "http://www.thehartford.com/blog/page9" -> "thehartford.com/blog/page9",
    "http://www.thehartford.com/blog/page10" -> "thehartford.com/blog/page10",
    "http://www.thehartford.com/blog/page11" -> "thehartford.com/blog/page11",
    "http://www.thehartford.com/blog/page12" -> "thehartford.com/blog/page12",
    "http://www.thehartford.com/blog/page13" -> "thehartford.com/blog/page13",
    "http://www.thehartford.com/blog/page14" -> "thehartford.com/blog/page14",
    "http://www.thehartford.com/blog/page15" -> "thehartford.com/blog/page15",
    "http://www.thehartford.com/blog/page16" -> "thehartford.com/blog/page16",
    "http://www.thehartford.com/blog/page17" -> "thehartford.com/blog/page17",
    "http://www.thehartford.com/blog/page18" -> "thehartford.com/blog/page18",
    "http://www.thehartford.com/blog/page19" -> "thehartford.com/blog/page19",
    "http://www.thehartford.com/blog/page20" -> "thehartford.com/blog/page20",
    "http://www.thehartford.com/blog/page21" -> "thehartford.com/blog/page21",
    "http://www.thehartford.com/blog/page22" -> "thehartford.com/blog/page22",
    "http://www.thehartford.com/blog/page23" -> "thehartford.com/blog/page23",
    "http://www.thehartford.com/blog/page24" -> "thehartford.com/blog/page24",
    "http://www.thehartford.com/blog/page25" -> "thehartford.com/blog/page25",
    "http://www.thehartford.com/corporate" -> "thehartford.com/corporate",
    "http://www.thehartford.com/corporate/comapany" -> "/comapany",
    "http://www.thehartford.com/corporate/comapany/whoweare" -> "/comapany/whoweare",
    "http://www.thehartford.com/corporate/comapany/howwemeetyourneeds" -> "/comapany/howwemeetyourneeds",
    "http://www.thehartford.com/corporate/comapany/whatsetsusapart" -> "/comapany/whatsetsusapart",
    "http://www.thehartford.com/corporate/contactus" -> "/contactus",
    "http://www.thehartford.com/corporate/news" -> "/news"
  )


  /** Makes sure only ERROR messages get logged to avoid log spam. */
  def setupLogging() = {
    import org.apache.log4j.{Level, Logger}
    val rootLogger = Logger.getRootLogger()
    rootLogger.setLevel(Level.ERROR)
  }

  /** Configures Twitter service credentials using twiter.txt in the main workspace directory */
  def setupTwitter() = {
    import scala.io.Source

    for (line <- Source.fromFile("../twitter.txt").getLines) {
      val fields = line.split(" ")
      if (fields.length == 2) {
        System.setProperty("twitter4j.oauth." + fields(0), fields(1))
      }
    }
  }

  def setupKafkaProducer(kafkaOutputBrokers: String): util.HashMap[String, Object] = {
    val props = new util.HashMap[String, Object]()
    props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, kafkaOutputBrokers)
    props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG,
      "org.apache.kafka.common.serialization.StringSerializer")
    props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG,
      "org.apache.kafka.common.serialization.StringSerializer")
    props
  }

  /** Retrieves a regex Pattern for parsing Apache access logs. */
  def apacheLogPattern(): Pattern = {
    val ddd = "\\d{1,3}"
    val ip = s"($ddd\\.$ddd\\.$ddd\\.$ddd)?"
    val client = "(\\S+)"
    val user = "(\\S+)"
    val dateTime = "(\\[.+?\\])"
    val request = "\"(.*?)\""
    val status = "(\\d{3})"
    val bytes = "(\\S+)"
    val referer = "\"(.*?)\""
    val agent = "\"(.*?)\""
    val regex = s"$ip $client $user $dateTime $request $status $bytes $referer $agent"
    Pattern.compile(regex)
  }
}